name: CI - Test and Build

on:
  push:
    branches: [develop]

permissions:
  actions: write    # Para disparar otros workflows
  contents: write # Para que pueda hacer checkout y quizás subir artefactos si se necesita
  packages: write # Para que pueda subir y bajar paquetes de Docker Hub o GitHub Packages
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Vote - Unit test
      - name: Vote - Prueba Unitaria & Cobertura
        working-directory: ./vote
        run: |
          pip install coverage
          coverage run --source=vote -m unittest tests/test_app.py
          coverage report
          coverage xml
        
      - name: Cargar cobertura Vote
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-vote
          path: ./vote/coverage.xml
      
      # Worker - Unit test
      - name: Worker - Prueba Unitaria & Cobertura
        working-directory: ./worker
        run: |
          npm ci
          npm test -- --coverage --coverageReporters=lcov

      - name: Cargar cobertura Worker
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-worker
          path: ./worker/coverage/lcov-report
      
      # Result - Unit test
      - name: Result - Prueba Unitaria & Cobertura
        working-directory: ./result
        run: |
          npm ci
          npm test -- --coverage --coverageReporters=lcov
      
      - name: Cargar cobertura Result
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-result
          path: ./result/coverage/lcov-report

  integration-tests:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Instalar jq para formatear JSON
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Ejecutar Docker Compose
        run: docker compose -f docker-compose.yml up -d
      
      - name: Esperar a que los servicios estén listos
        run: |
          chmod +x ./scripts/wait-for-services.sh
          ./scripts/wait-for-services.sh

      - name: Asegurar permisos del script de integración
        run: chmod +x ./scripts/integrationTest.sh
      
      - name: Ejecutar pruebas de integración
        run: ./scripts/integrationTest.sh

      - name: Tear down
        if: always()
        run: docker compose down

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Vote image (latest)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest -f vote/Dockerfile.vote.test ./vote
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

      - name: Build & Push Worker image (latest)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest -f worker/Dockerfile.worker.test ./worker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

      - name: Build & Push Result image (latest)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest -f result/Dockerfile.result.test ./result
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest
