name: CI - Test and Build

on:
  push:
    branches: [develop]

permissions:
  actions: write    # Para disparar otros workflows
  contents: write # Para que pueda hacer checkout y quizás subir artefactos si se necesita
#  packages: write # Para que pueda subir y bajar paquetes de Docker Hub o GitHub Packages
  
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Vote - Unit test
      - name: Vote - Prueba Unitaria & Cobertura
        working-directory: ./vote
        run: |
          pip install coverage
          coverage run --source=vote -m unittest tests/test_app.py
          coverage report
          coverage xml
        
      - name: Cargar cobertura Vote
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-vote
          path: ./vote/coverage.xml
      
      # Worker - Unit test
      - name: Worker - Prueba Unitaria & Cobertura
        working-directory: ./worker
        run: |
          npm ci
          npm test -- --coverage --coverageReporters=lcov

      - name: Cargar cobertura Worker
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-worker
          path: ./worker/coverage/lcov-report
      
      # Result - Unit test
      - name: Result - Prueba Unitaria & Cobertura
        working-directory: ./result
        run: |
          npm ci
          npm test -- --coverage --coverageReporters=lcov
      
      - name: Cargar cobertura Result
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-result
          path: ./result/coverage/lcov-report

  integration-tests:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Instalar jq para formatear JSON
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Ejecutar Docker Compose
        run: docker compose -f docker-compose.yml up -d
      
      - name: Esperar a que los servicios estén listos
        run: |
          chmod +x ./scripts/wait-for-services.sh
          ./scripts/wait-for-services.sh

      - name: Asegurar permisos del script de integración
        run: chmod +x ./scripts/integrationTest.sh
      
      - name: Ejecutar pruebas de integración
        run: ./scripts/integrationTest.sh

      - name: Tear down
        if: always()
        run: docker compose down

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Vote image (latest)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest -f vote/Dockerfile.vote.test ./vote
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

      - name: Build & Push Worker image (latest)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest -f worker/Dockerfile.worker.test ./worker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

      - name: Build & Push Result image (latest)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest -f result/Dockerfile.result.test ./result
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

          # --> NUEVO PASO CRUCIAL PARA DISPARAR EL WORKFLOW DEPLOY-STAGING CON EL PAT <--
      - name: Disparar workflow de despliegue a Staging via GitHub API
        # Solo se ejecuta si el job 'docker-build-and-push' es exitoso
        if: success()
        run: |
          # Construye la URL de la API para disparar el workflow.
          # ${{ github.repository }} se expande a 'mi-usuario/mi-repositorio'
          # El nombre del archivo del workflow es 'deploy-staging.yml'
          # API_URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-staging/dispatches"
          API_URL="https://api.github.com/repos/rodvel-inc/githubActions2/actions/workflows/deploy-staging/dispatches"
          
          # ${{ github.ref_name }} obtendrá el nombre corto de la rama (ej. 'develop')
          BRANCH_TO_DEPLOY="${{ github.ref_name }}" 

          echo "Intentando disparar el workflow deploy-staging.yml en la rama $BRANCH_TO_DEPLOY..."
          
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT_WORKFLOW_TRIGGER }}" \
            -d "{\"ref\":\"$BRANCH_TO_DEPLOY\"}" \
            "$API_URL"
          
          echo "Comando cURL ejecutado. Por favor, revisa la pestaña 'Actions' para ver una nueva ejecución de Auto-Deploy a Staging."